spring:
    application:
        name: "configserver"
    profiles:
        active: git
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Masthan555/eazybank-config.git
                    default-label: master
                    timeout: 5
                    clone-on-start: true
                    force-pull: true
                #native:
                    #search-locations: "classpath:/config/"
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

encrypt:
  key: "12345678901234567890123456789012"

server:
    port: 8888

management:
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true
    micrometer:
        tags:
            application: ${spring.application.name}